# Site settings
title: "👻 \  DEADCODEXO \  👋"
SEOTitle: "DeadCodeXO's Blog"
header-img: img/post-bg-about.jpg
email: deadcodexo@gmail.com
description: "dowhatnow?"
keyword: "ayocaine, deadcodexo, blog, arch linux, github"
url: "https://deadcodexo.github.io"
baseurl: ""

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
github_username: deadcodexo
twitter_username: deadcodexo
facebook_username: deadcodexo
linkedin_username: deadcodexo

# Build settings
highlighter: rouge
permalink: pretty
paginate: 10
exclude: [
  "less",
  "node_modules",
  "Gruntfile.js",
  "package.json",
  "README.md",
  "README.zh.md"
]
anchorjs: true

# Gems
plugins: [jekyll-paginate]

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
# disqus_username: hynduf

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
# ga_track_id: "UA-49627206-1"
# ga_domain: huangxuan.me

# Sidebar settings
sidebar: true
sidebar-about-description: "just a below average ghost, <br/> trapped inside a PC, <br/> who streams on <a href=\"https://twitch.tv/deadcodexo\">twitch.tv</a>"
sidebar-avatar: https://i.imgur.com/zGXzAQt.png

# Featured Tags
featured-tags: true
featured-condition-size: 0

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

collections:
  projects:
    output: true
# Friends
friends:
  [
    { title: "Dead Code", href: "https://deadcodexo.github.io/" },
  ]

