backend:
  name: github
  repo: deadcodeXO/deadcodexo.github.io
  branch: main

local_backend: true

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: blog
    label: Blog
    folder: src/data/blog
    create: true
    extension: md
    format: frontmatter
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: text }
      - { label: Publish Date, name: pubDatetime, widget: datetime }
      - { label: Modified Date, name: modDatetime, widget: datetime, required: false }
      - { label: Author, name: author, widget: string, default: DEADCODEXO }
      - { label: Featured, name: featured, widget: boolean, default: false, required: false }
      - { label: Draft, name: draft, widget: boolean, default: false, required: false }
      - { label: Tags, name: tags, widget: list, default: [others] }
      - { label: Open Graph Image, name: ogImage, widget: image, required: false }
      - { label: Canonical URL, name: canonicalURL, widget: string, required: false }
      - { label: Hide Edit Post Link, name: hideEditPost, widget: boolean, default: false, required: false }
      - { label: Timezone, name: timezone, widget: string, required: false }
      - { label: Body, name: body, widget: markdown }

  - name: galleries
    label: Galleries
    folder: src/data/galleries
    create: true
    extension: md
    format: frontmatter
    slug: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: text }
      - { label: Publish Date, name: pubDatetime, widget: datetime }
      - { label: Draft, name: draft, widget: boolean, default: false, required: false }
      - { label: Tags, name: tags, widget: list, default: [] }
      - { label: Cover Image, name: coverImage, widget: image, required: false }
      - { label: Body, name: body, widget: markdown, required: false }

  - name: pages
    label: Pages
    folder: src/pages
    create: true
    extension: md
    format: frontmatter
    slug: "{{slug}}"
    fields:
      - { label: Layout, name: layout, widget: hidden, default: ../layouts/PageLayout.astro }
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: text, required: false }
      - { label: Body, name: body, widget: markdown }
